---
- name: RETRIEVE WORKER NODE DETAILS FROM KUBERNETES NODE
  hosts: all
  gather_facts: no

  collections: 
    - community.kubernetes
  
  tasks:
  - name: GET WORKER NODE DETAILS
    community.kubernetes.k8s_info:
      kind: Node
      namespace: default 
  - name: Create a k8s namespace
    community.kubernetes:
      kind: Namespace
      name: testing
      api_version: v1
      state: present
    
