apiVersion: v1
kind: Service
metadata:
  name: {{ portallocalvars.name }}ser
  namespace: {{ portallocalvars.namespace }}
spec:
  ports:
  - port: {{ portallocalvars.serviceport }}
    targetPort: {{ portallocalvars.podport }}
    nodePort: {{ portallocalvars.nodeport }}
    protocol: TCP
  selector:
    app: {{ portallocalvars.name }}
    version: {{ portallocalvars.version }}
  type: NodePort

